#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.36213
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CommonFramework.Resource", IsApplication=true)]

namespace CommonFramework
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PsMono.Core.Resource.String.ApplicationName = global::CommonFramework.Resource.String.ApplicationName;
			global::PsMono.Core.Resource.String.Hello = global::CommonFramework.Resource.String.Hello;
			global::PsMono.Zlib.Resource.String.ApplicationName = global::CommonFramework.Resource.String.ApplicationName;
			global::PsMono.Zlib.Resource.String.Hello = global::CommonFramework.Resource.String.Hello;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int loading = 2130968576;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060006
			public const int black_translucent = 2131099654;
			
			// aapt resource value: 0x7f060002
			public const int blue_light = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int blue_weight = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int lightwhite = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int red = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int touming = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int white = 2131099649;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int badge_ifaux = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int btn_check_off = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int btn_check_off_pressed = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int btn_check_off_selected = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int btn_check_on = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int btn_check_on_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int btn_check_on_selected = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int btn_login_style = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int default_bg = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Icon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int input_over = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int loading1 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int loading2 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int loading3 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int loading_bg = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int loading_drawable = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int loading_progress_draw = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int loadingdialog_bg = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int login_back = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int login_button_nor = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int login_button_press = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int login_input = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int qq_btn_check = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int qq_checkbox_text_color = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int qq_edit_login = 2130837528;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080006
			public const int LinearLayout01 = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int RelativeLayout02 = 2131230727;
			
			// aapt resource value: 0x7f08000c
			public const int TableLayout01 = 2131230732;
			
			// aapt resource value: 0x7f080009
			public const int TextView01 = 2131230729;
			
			// aapt resource value: 0x7f08000b
			public const int TextView02 = 2131230731;
			
			// aapt resource value: 0x7f08000e
			public const int linearLayout1 = 2131230734;
			
			// aapt resource value: 0x7f08000f
			public const int linearLayout2 = 2131230735;
			
			// aapt resource value: 0x7f080002
			public const int loading_layout = 2131230722;
			
			// aapt resource value: 0x7f080004
			public const int loading_msg = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int loading_progress = 2131230723;
			
			// aapt resource value: 0x7f080005
			public const int loginRoot = 2131230725;
			
			// aapt resource value: 0x7f08000d
			public const int login_btn_loginnew = 2131230733;
			
			// aapt resource value: 0x7f080008
			public const int login_edit_account = 2131230728;
			
			// aapt resource value: 0x7f08000a
			public const int login_edit_pwd = 2131230730;
			
			// aapt resource value: 0x7f080001
			public const int mainlayout = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int webView1 = 2131230720;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int detail = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int loading = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int loadingdialog = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int login = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int main = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050008
			public const int appname = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int loading = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int login = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int opt_remember = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int strAccInputLabel = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int strInputAccHint = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int strInputpwdHint = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int strPswInputLabel = 2131034117;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int AppBaseTheme = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int AppTheme = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int LoadingTheme = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int MyCheckBox = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int dialog = 2131165189;
			
			// aapt resource value: 0x7f070000
			public const int loading = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
